export const departaments = [
  { name: 'Amazonas' },
  { name: 'Áncash' },
  { name: 'Apurímac' },
  { name: 'Arequipa' },
  { name: 'Ayacucho' },
  { name: 'Cajamarca' },
  { name: 'Callao' },
  { name: 'Cusco' },
  { name: 'Huancavelica' },
  { name: 'Huánuco' },
  { name: 'Ica' },
  { name: 'Junín' },
  { name: 'La Libertad' },
  { name: 'Lambayeque' },
  { name: 'Lima' },
  { name: 'Loreto' },
  { name: 'Madre de Dios' },
  { name: 'Moquegua' },
  { name: 'Pasco' },
  { name: 'Piura' },
  { name: 'Puno' },
  { name: 'San Martín' },
  { name: 'Tacna' },
  { name: 'Tumbes' },
  { name: 'Ucayali' },
];

export const provinces = [
  { name: 'Chachapoyas' },
  { name: 'Bagua' },
  { name: 'Utcubamba' },
  { name: 'Huaraz' },
  { name: 'Carhuaz' },
  { name: 'Yungay' },
  { name: 'Abancay' },
  { name: 'Andahuaylas' },
  { name: 'Aymaraes' },
];

export const districts = [
  { name: 'Chachapoyas' },
  { name: 'Asunción' },
  { name: 'Balsas' },
  { name: 'Huaraz' },
  { name: 'Carhuaz' },
  { name: 'Yungay' },
  { name: 'Abancay' },
  { name: 'Chacoche' },
  { name: 'Circa' },
  // Puedes continuar agregando más distritos según sea necesario
];
